### ISSUE TITLE
Как запустить GCB и Pvpgn на 6112 порту но с разными IP

### ISSUE THREAD

**Issue by Artyom91** [HarpyWar/pvpgn#129]
@HarpyWar Здравствуйте, помогите пожалуйста. Я вот тут задал свой вопрос, до сих пор не помогли https://github.com/uakfdotb/gcb/issues/27 .

В чем суть, нужно как-то GCB профиксить что бы он слушал IP который указан в настройке, сейчас он работает так:

![2014-12-31_134909](https://cloud.githubusercontent.com/assets/6318282/5585334/d9bb1c8e-90f3-11e4-9985-9db5f46f2261.png)

Pvpgn в свою очередь работает нормально:

![2014-12-31_135102](https://cloud.githubusercontent.com/assets/6318282/5585349/1bc4222e-90f4-11e4-94f1-fee01acfef6d.png)

@HarpyWar Можете посмотреть код GCB и написать исправление, нужно просто вставить в код, который отвечает за IP, с которого работает GCB.

**Comment by HarpyWar** [comment]
Я не знаком с этим проектом и не знаю как он работает. Судя по исходникам, строка адреса из конфига должна успешно парситься, и сервер должен запускаться по указанному адресу в `gcb_bindaddress` . В случае неуспеха в консоль должны выводиться ошибки (следует установить `gcb_loglevel = 4096`, чтобы получить детали).

Варианты решения:
а) Так как в логах отображается `udp6` и `:::`, то скорее всего сервер запускается на интерфейсе ipv6 вместо ipv4. Если ipv6 нигде больше не используется, то его можно попробовать полностью отключить в системе.

б) Если первым запустить pvpgn на одном из IP с портом 6112, а вторым запустить  gcb на всех IP, то gcb не сможет использовать уже занятый порт, используемый pvpgn. Соответственно, gcb должен запуститься на других IP со свободным портом 6112, и оба сервера будут работать на разных IP с одинаковым портом.

**Comment by Artyom91** [comment]
@HarpyWar Отключил полностью IP v6, запустил на порту 6112 только работу GCB, ввожу команду netstat -tpln | grep 6112 и ничего не выводит, хотя GCB работает и пакеты отправляются.

Отключил GCB, запустил pvpgn, включаю GCB - не запускается.

Что не так?

**Comment by HarpyWar** [comment]
netstat -tpln | grep 6112 ничего не выводит наверное потому, что для вывода udp сокетов нужно использовать ключ -u вместо -t?

Если во втором случае не запускается, то ничем помочь не могу. Обычное поведение программы в этом случае должно быть как я описал выше &mdash; то есть, игнорировать несвободные IP и запускаться на свободных (конечно же, если на машине уже имеются несколько IP адресов). Можно добавить об этом в той теме, созданной на странице проекта.

Там же советую приложить детализированные логи с конфигом, когда в конфиге явно указан IP адрес, на котором gcb должен запускаться, но запускается он почему-то на всех сетевых интерфейсах. Сейчас ведь другой лог после отключения ipv6? Заодно приложить вывод `netstat`, подтверждающий запуск на всех интерфейсах..
Не исключаю, что причина, по которой это происходит, соответствует описанной мною в последнем сообщении той темы.

**Comment by Artyom91** [comment]
@HarpyWar Да, всё ок, ip v4 стало, но ip всё равно не указан, в настройках указал.

![2015-01-31_070556](https://cloud.githubusercontent.com/assets/6318282/5983289/b274dba6-a917-11e4-9dbf-a559359caf24.png)

**Comment by HarpyWar** [comment]
gcb может быть как-то использован в связке с pvpgn, или он работает в качестве клиентского приложения?

**Comment by Artyom91** [comment]
@HarpyWar GCB - это приложение, через которое Ghost отправляет пакеты в Garena и тем самым люди в гарене могут играть через него на боте.

Вот залил лог, Там ничего интересного http://rghost.ru/8v4D2GzK4

**Comment by HarpyWar** [comment]
Как я уже написал выше, лучше спросить разработчиков как сделать привязку на один IP, приложив всю имеющуюся информацию, включая конфиг.

**Comment by Artyom91** [comment]
@HarpyWar Помогите пожалуйста, вот мне подсказали https://github.com/uakfdotb/gcb/issues/28 я заменил

socket = new DatagramSocket(broadcast_port);

на

socket = 149.154.66.19:6112;

Всё тоже самое...
