### ISSUE TITLE
Replace sprintf() with snprintf()

### ISSUE THREAD

**Issue by xboi209** [HarpyWar/pvpgn#132]
````snprintf()```` is better and we should consistently choose one or the other. Possibly throw an error whenever someone tries to compile ````sprintf()````?

**Comment by HarpyWar** [comment]
I agree, there are also several functions like `strcat`, `strcpy` should be replaced to the safer "n" alternative. I need someone who can do this work.
Referenced to https://github.com/HarpyWar/pvpgn/issues/50

**Comment by xboi209** [comment]
https://github.com/HarpyWar/pvpgn/blob/master/src/compat/snprintf.h#L25
I don't think we should define ````_snprintf()````(Microsoft's implementation) as ````snprintf()```` because it behaves differently.

**Comment by HarpyWar** [comment]
I don't know much about these matters (including https://github.com/HarpyWar/pvpgn/issues/131). I could be wrong, but I think it was made for the cross platform compatibility. Could you explain more about changes that you suggest?

Also there is an error in VS2013 if comment this line:
```
Error	1	error C3861: 'snprintf': identifier not found	src\common\conf.cpp	93	1	common
```

**Comment by Kelwing** [comment]
On a related note, it might be good to replace char arrays with strings.  It's a C++ project, there is no reason to be using character arrays to store string values unless you're writing a library intended to be compiled statically.

**Comment by xboi209** [comment]
@HarpyWar
Microsoft previously didn't provide a standard compliant ````snprintf```` but decided to write their own implementation which behaves differently.
Since we should have consistent behavior, we shouldn't use ````_snprintf```` and instead use the implementation defined in ````compat/snprintf.cpp````(although I'm not sure if that implementation exactly imitates the standard ````snprintf```` behavior).

**Comment by Kelwing** [comment]
I'd be happy to slowly do it in my spare time.

**Comment by xboi209** [comment]
Microsoft only recently provided an implementation for ````snprintf````(June of 2014, in Visual Studio 2015 which is still in beta).
The ````compat/snprintf.cpp```` provides its own implementation when ````snprintf```` and ````_snprintf```` is unimplemented.

**Comment by HarpyWar** [comment]
@Kelwing this is good suggestion, we will wait for your pull requests!
Changes for strings may need testing of each modification, not to accidentally break functionality.

**Comment by Kelwing** [comment]
Right, I will be testing it as I go.
