### ISSUE TITLE
Request Branch for not Cache User database

### ISSUE THREAD

**Issue by anonprophet** [HarpyWar/pvpgn#136]
i want make private server, can i request a branch 
for not cache user database, like password field

i want update via web php, like register, reset password, change password, etc.
so everytime user login in pvpgn, its retrieve data from database, not cache

**Comment by HarpyWar** [comment]
Instead you can use use bot login with commands like `/addacct`, `/chpass` etc.
Look into the example 
http://pvpgn.harpywar.com/pvpgn_bot.class.php
http://pvpgn.harpywar.com/pvpgn_bot.class.txt

**Comment by anonprophet** [comment]
thanks for suggestion harpywar,

btw i test that script on my pc localhost, i change only the $login and $password
but its always loading

Fatal error: Maximum execution time of 5 seconds exceeded in C:\xampp\htdocs\pvpgn\bot.php on line 65
error catched!

could you tell me where im wrong ?

**Comment by cen1** [comment]
1. You can make a command queue. Have the website leave the commands in a database and execute them on the backend either periodically or with an invoke.
2. Bot is just a normal user, so no extra ports.

**Comment by anonprophet** [comment]
thanks, i will do it using database and queue that command.

**Comment by anonprophet** [comment]
@HarpyWar when i use this script on my VPS (same server with pvpgn) it's cant login
when i try the script on my PC. success

please help me.

**Comment by HarpyWar** [comment]
@anonprophet Check your PHP configuration, `sockets` extension must be enabled in `php.ini`. 
No errors may be because PHP doesn't configured to show error messages.

**Comment by anonprophet** [comment]
thanks fixed, im wrong in password field, i see it when display_error.
