### ISSUE TITLE
Visual Studio project files

### ISSUE THREAD

**Issue by xboi209** [HarpyWar/pvpgn#145]
For easier development in Visual Studio instead of using the ones generated by cmake.

**Comment by cen1** [comment]
What's wrong with cmake generated ones?

**Comment by xboi209** [comment]
It seems less organized. For example, I don't want something like common and compat to be in separate projects, they should be under the same project.

**Comment by cen1** [comment]
If project files need to be reorganized in some way I suggest we do that in Cmake so Cmake can then generate the project files the  way you want them. I will take a look how to combine two source folders into a single project.

**Comment by cen1** [comment]
Both projects produce their own library: common.lib and compat.lib. Is it even possible to produce two different binaries from a single VS project? I've never done anything like that.
