### ISSUE TITLE
Save topics for non-permanent channels

### ISSUE THREAD

**Issue by xboi209** [HarpyWar/pvpgn#171]
Currently, PvPGN saves topics to ````topics.conf```` only if the channel is a permanent channel. This means that any non-permanent channel will lose their topics when the server shuts down. Should topics be saved for all channels or keep the current functionality?

If no one objects, I'll make PvPGN save topics for all channels.

**Comment by HarpyWar** [comment]
Temporary channel's topic should not be saved into a file, because it's temporary. All servers that I see before save any data of non-permanent objects in memory only.
Any reason why you want to save all channels?

**Comment by xboi209** [comment]
Okay then, I was just doing an overhaul of the topics system.
